services:
  postgresdb:
    image: postgres:17-alpine3.20
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wishbot
    volumes:
      - db_data:/var/lib/postgresql/data  
    ports:
      - "5434:5434"
    restart: always

  wishbot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Almaty
      - WISHBOT_TELEGRAM_TOKEN=7198871252:AAGvf9Hk8XHa43wLeXu8dtX1CxbqG6stz8o
    depends_on:
      - postgresdb
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia:/usr/share/zoneinfo/Asia:ro

volumes:
  db_data:    