// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type DimFriendStatus struct {
	ID         int32  `json:"id"`
	StatusName string `json:"status_name"`
}

type DimWishStatus struct {
	ID         int32  `json:"id"`
	StatusName string `json:"status_name"`
}

type Friend struct {
	ChatID    int32     `json:"chat_id"`
	FriendID  int32     `json:"friend_id"`
	Status    int32     `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	Username  string    `json:"username"`
	ChatID    int32     `json:"chat_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Wish struct {
	ID          int32     `json:"id"`
	ChatID      int32     `json:"chat_id"`
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	Link        string    `json:"link"`
	Status      string    `json:"status"`
}
