// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friend, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWish(ctx context.Context, arg CreateWishParams) (Wish, error)
	DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error
	DeleteUser(ctx context.Context, chatID int32) error
	DeleteWish(ctx context.Context, arg DeleteWishParams) error
	GetAprovedFriendships(ctx context.Context, chatID int32) ([]GetAprovedFriendshipsRow, error)
	GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friend, error)
	GetPendingFriendships(ctx context.Context, chatID int32) ([]GetPendingFriendshipsRow, error)
	GetUser(ctx context.Context, chatID int32) (User, error)
	GetWishesForUser(ctx context.Context, chatID int32) ([]Wish, error)
	GetWishesPublic(ctx context.Context, arg GetWishesPublicParams) ([]GetWishesPublicRow, error)
	UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) (Friend, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateWish(ctx context.Context, arg UpdateWishParams) (Wish, error)
	UpdateWishStatus(ctx context.Context, arg UpdateWishStatusParams) (Wish, error)
}

var _ Querier = (*Queries)(nil)
