app:
  environment: dev
postgres:
  host: postgresdb:5432
  database: wishbot
  userName: root
  password: password
  sslMode: disable
api:
  port: "8080"
telegram:
  token: 7198871252:AAGvf9Hk8XHa43wLeXu8dtX1CxbqG6stz8o
  admins: [855588888, 7777777777]
  