app:
  environment: stage
migrations:
  migrate: false
postgres:
  host: postgresdb:5432
  database: wishbot
  userName: root
  password: password
  sslMode: disable
api:
  port: "8080"
telegram:
  token: 111111111111111111111111111111111111111
  admins: [855588888, 7777777777]
  