app:
  environment: stage
  photos: ./photos
migrations:
  migrate: true
postgres:
  host: postgresdb:5432
  database: wishbot
  userName: root
  password: password
  sslMode: disable
api:
  port: "8081"
telegram:
  token: 111111111111111111111111111111111111111
  admin: wkcb0J2r5YjfxfXa15aDoxWjUfvd5LjPp7
  