// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_info.sql

package db

import (
	"context"
)

const getUserInfo = `-- name: GetUserInfo :one
SELECT chat_id, address, phone, name, description, created_at, updated_at FROM user_info
WHERE chat_id = $1 LIMIT 1
`

func (q *Queries) GetUserInfo(ctx context.Context, chatID int64) (UserInfo, error) {
	row := q.db.QueryRow(ctx, getUserInfo, chatID)
	var i UserInfo
	err := row.Scan(
		&i.ChatID,
		&i.Address,
		&i.Phone,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
